### ISSUE TITLE
General

### ISSUE THREAD

**Issue by AlejandroVS2015** [AsmusGerman/IMA#19]
- [ ] Aparece mensaje de error diciendo que el sistema no posee ningún año lectivo cargado, cuando el usuario inicia sesión, a pesar de que existan años lectivos cargados.

**Comment by AsmusGerman** [comment]
- [ ] agregar contenido en la página principal bajo el título **"Todo lo que puedes hacer"**

**Comment by AsmusGerman** [comment]
<h1 id="introduccion">Introducción</h1>
<p>Brevemente veremos los principales elementos con los que se puede interactuar dentro de la aplicación.</p>
<p>Comenzaremos con la estructura básica y sus componentes, para qué sirven y qué puede hacer con ellos.</p>
<p>¡Verá qué sencillo es!</p>
<h2 id="estructura-basica">Estructura básica</h2>
<p>La aplicación está dividida en la <strong>barra superior</strong>, el <strong>menú lateral</strong> y el <strong>sector de contenido dinámico</strong>.</p>
<p>Todo lo que necesitemos hacer, podremos resolverlo usando los componentes proporcionados en estas secciones.</p>
<h3 id="barra-superior">Barra superior</h3>
<p>Como indica su nombre, la <strong>barra superior</strong> se encuentra al comienzo de la pantalla y en ella podremos encontrar:</p>
<ul>
<li><em>&quot;Instituto María Auxiliadora&quot;</em>: es el título principal de la aplicación y a si hacemos click sobre él, siempre nos llevará a la pantalla principal.</li>
<li><em>&quot;Cerrar sesión&quot;</em>: es un botón y si hacemo click sobre él, saldremos de la aplicación.</li>
</ul>
<p>A su vez, pordremos ver un mensaje de bienvenida que dirá <em>&quot;Hola...!&quot;</em> y en él nuestro nombre.</p>
<h3 id="menu-lateral">Menú lateral</h3>
<p>El <strong>menú lateral</strong> lo podremos encontrar a la izquierda de la pantalla y en él, varias opciones seccionadas bajo las etiquetas <small><em>&quot;ADMINISTRACIÓN&quot;</em></small>, <small><em>&quot;ACADÉMICO&quot;</em></small> y <small><em>&quot;CONTADURÍA&quot;</em></small>.</p>
<p>Así se nos hará más sencillo. Siempre es mejor que esté bien ordenado, ¿no?</p>
<h4 id="el-menu-basico">El menú básico</h4>
<p>Según el tipo de usuario, el menú puede variar, el caso base que encontraremos tendrá la siguiente forma:</p>
<ul>
<li>ADMINISTRACIÓN
<ul>
<li>Año lectivo</li>
<li>Grados</li>
<li>Usuarios</li>
</ul>
</li>
<li>ACADÉMICO
<ul>
<li>Alumnos</li>
<li>Cursos</li>
<li>Inscripciones</li>
</ul>
</li>
<li>CONTADURÍA
<ul>
<li>Cuotas</li>
<li>Inscripciones</li>
<li>Pagos</li>
</ul>
</li>
</ul>
<p>* para entender sobre cada una de las opciones, haz click sobre la opción correspondiente en el <strong>menú lateral</strong>.</p>
<h3 id="sector-de-contenido-dinamico">Sector de contenido dinámico</h3>
<p>En esta sección aparecerá contenido de forma dinámica según la opción que haya seleccionado anteriormente.
Como sucede ahora, el texto que se muestra apareció inmediatamente después de que seleccionó la opción <em>&quot;Introducción&quot;</em>, de la pantalla principal.</p>
<p>Si ahora seleccionamos alguna opción del <strong>menú principal</strong>, el contenido de esta sección cambiará.
Así, cada vez que seleccionemos una opción del menú, hagamos click sobre el título de la barra superior o en alguna otra opción que pueda darse dentro del sector de contenido dinámico.</p>

**Comment by facurodriguez** [comment]
Se corrige en https://github.com/AsmusGerman/IMA/commit/6654430dae901d9b9242e22b1cd52050a9885398
